- name: Определить архитектуру и создать папку
  hosts: all
  gather_facts: true

  tasks:
    - name: Проверить есть ли /etc
      ansible.builtin.stat:
        path: /etc
      register: etc_check

    - name: Узнатиь платформу
      ansible.builtin.set_fact:
        is_debian: "{{ ansible_distribution == 'Debian' }}"
      
    - name: Вывод сведений
      ansible.builtin.debug:
        msg: |
          /etc существует? {{ etc_check.stat.exists }}
          OS = {{ ansible_distribution }}
          Debian? {{ is_debian }}